package com.hiroshi.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COMIC_RECORD".
 */
public class ComicRecord {

    private Long id;
    private int source;
    /** Not-null value. */
    private String path;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String image;
    /** Not-null value. */
    private String update;
    private Long favorite;
    private Long history;
    private String last_path;
    private Integer last_page;

    public ComicRecord() {
    }

    public ComicRecord(Long id) {
        this.id = id;
    }

    public ComicRecord(Long id, int source, String path, String title, String image, String update, Long favorite, Long history, String last_path, Integer last_page) {
        this.id = id;
        this.source = source;
        this.path = path;
        this.title = title;
        this.image = image;
        this.update = update;
        this.favorite = favorite;
        this.history = history;
        this.last_path = last_path;
        this.last_page = last_page;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getSource() {
        return source;
    }

    public void setSource(int source) {
        this.source = source;
    }

    /** Not-null value. */
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath(String path) {
        this.path = path;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getImage() {
        return image;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImage(String image) {
        this.image = image;
    }

    /** Not-null value. */
    public String getUpdate() {
        return update;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdate(String update) {
        this.update = update;
    }

    public Long getFavorite() {
        return favorite;
    }

    public void setFavorite(Long favorite) {
        this.favorite = favorite;
    }

    public Long getHistory() {
        return history;
    }

    public void setHistory(Long history) {
        this.history = history;
    }

    public String getLast_path() {
        return last_path;
    }

    public void setLast_path(String last_path) {
        this.last_path = last_path;
    }

    public Integer getLast_page() {
        return last_page;
    }

    public void setLast_page(Integer last_page) {
        this.last_page = last_page;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof ComicRecord && ((ComicRecord) o).id.equals(id);
    }
}
