package com.hiroshi.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FAVORITE_COMIC".
 */
public class FavoriteComic {

    private Long id;
    private String title;
    private String image;
    private Integer source;
    private String update;
    private String path;
    private Long create;
    private String last_path;
    private String last_page;

    public FavoriteComic() {
    }

    public FavoriteComic(Long id) {
        this.id = id;
    }

    public FavoriteComic(Long id, String title, String image, Integer source, String update, String path, Long create, String last_path, String last_page) {
        this.id = id;
        this.title = title;
        this.image = image;
        this.source = source;
        this.update = update;
        this.path = path;
        this.create = create;
        this.last_path = last_path;
        this.last_page = last_page;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Integer getSource() {
        return source;
    }

    public void setSource(Integer source) {
        this.source = source;
    }

    public String getUpdate() {
        return update;
    }

    public void setUpdate(String update) {
        this.update = update;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getCreate() {
        return create;
    }

    public void setCreate(Long create) {
        this.create = create;
    }

    public String getLast_path() {
        return last_path;
    }

    public void setLast_path(String last_path) {
        this.last_path = last_path;
    }

    public String getLast_page() {
        return last_page;
    }

    public void setLast_page(String last_page) {
        this.last_page = last_page;
    }

}
