package com.hiroshi.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hiroshi.db.entity.StarComic;

import com.hiroshi.db.dao.StarComicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig starComicDaoConfig;

    private final StarComicDao starComicDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        starComicDaoConfig = daoConfigMap.get(StarComicDao.class).clone();
        starComicDaoConfig.initIdentityScope(type);

        starComicDao = new StarComicDao(starComicDaoConfig, this);

        registerDao(StarComic.class, starComicDao);
    }
    
    public void clear() {
        starComicDaoConfig.getIdentityScope().clear();
    }

    public StarComicDao getStarComicDao() {
        return starComicDao;
    }

}
