package com.hiroshi.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hiroshi.db.entity.ComicRecord;

import com.hiroshi.db.dao.ComicRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig comicRecordDaoConfig;

    private final ComicRecordDao comicRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        comicRecordDaoConfig = daoConfigMap.get(ComicRecordDao.class).clone();
        comicRecordDaoConfig.initIdentityScope(type);

        comicRecordDao = new ComicRecordDao(comicRecordDaoConfig, this);

        registerDao(ComicRecord.class, comicRecordDao);
    }
    
    public void clear() {
        comicRecordDaoConfig.getIdentityScope().clear();
    }

    public ComicRecordDao getComicRecordDao() {
        return comicRecordDao;
    }

}
