package com.hiroshi.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hiroshi.db.entity.FavoriteComic;

import com.hiroshi.db.dao.FavoriteComicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteComicDaoConfig;

    private final FavoriteComicDao favoriteComicDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteComicDaoConfig = daoConfigMap.get(FavoriteComicDao.class).clone();
        favoriteComicDaoConfig.initIdentityScope(type);

        favoriteComicDao = new FavoriteComicDao(favoriteComicDaoConfig, this);

        registerDao(FavoriteComic.class, favoriteComicDao);
    }
    
    public void clear() {
        favoriteComicDaoConfig.getIdentityScope().clear();
    }

    public FavoriteComicDao getFavoriteComicDao() {
        return favoriteComicDao;
    }

}
