package com.hiroshi.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.hiroshi.db.entity.FavoriteComic;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FAVORITE_COMIC".
*/
public class FavoriteComicDao extends AbstractDao<FavoriteComic, Long> {

    public static final String TABLENAME = "FAVORITE_COMIC";

    /**
     * Properties of entity FavoriteComic.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Image = new Property(2, String.class, "image", false, "IMAGE");
        public final static Property Source = new Property(3, Integer.class, "source", false, "SOURCE");
        public final static Property Update = new Property(4, String.class, "update", false, "UPDATE");
        public final static Property Path = new Property(5, String.class, "path", false, "PATH");
        public final static Property Create = new Property(6, Long.class, "create", false, "CREATE");
        public final static Property Last_path = new Property(7, String.class, "last_path", false, "LAST_PATH");
        public final static Property Last_page = new Property(8, Integer.class, "last_page", false, "LAST_PAGE");
    };


    public FavoriteComicDao(DaoConfig config) {
        super(config);
    }
    
    public FavoriteComicDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FAVORITE_COMIC\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"IMAGE\" TEXT," + // 2: image
                "\"SOURCE\" INTEGER," + // 3: source
                "\"UPDATE\" TEXT," + // 4: update
                "\"PATH\" TEXT," + // 5: path
                "\"CREATE\" INTEGER," + // 6: create
                "\"LAST_PATH\" TEXT," + // 7: last_path
                "\"LAST_PAGE\" INTEGER);"); // 8: last_page
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FAVORITE_COMIC\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FavoriteComic entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(3, image);
        }
 
        Integer source = entity.getSource();
        if (source != null) {
            stmt.bindLong(4, source);
        }
 
        String update = entity.getUpdate();
        if (update != null) {
            stmt.bindString(5, update);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(6, path);
        }
 
        Long create = entity.getCreate();
        if (create != null) {
            stmt.bindLong(7, create);
        }
 
        String last_path = entity.getLast_path();
        if (last_path != null) {
            stmt.bindString(8, last_path);
        }
 
        Integer last_page = entity.getLast_page();
        if (last_page != null) {
            stmt.bindLong(9, last_page);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FavoriteComic readEntity(Cursor cursor, int offset) {
        FavoriteComic entity = new FavoriteComic( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // image
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // source
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // update
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // path
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // create
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // last_path
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // last_page
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FavoriteComic entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSource(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setUpdate(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPath(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCreate(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setLast_path(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setLast_page(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FavoriteComic entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FavoriteComic entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
